    const mongoose = require('mongoose')
    const CreateShowSchema = new mongoose.Schema({
        title:{
            type:String,
            required:true,
            maxlength:100,
        },
        tagline:{
            type:String,
            required:true,
            trim:true,
            maxlength:250,
        },
        releasedate:{
            type:String,
            required:true
        },
        genre:{
            type:mongoose.Schema.Types.ObjectId,
            ref:'Genre',
        },
        SUbGenre:[{
            type:mongoose.Schema.Types.ObjectId,
            ref:'SubGeneres',
        }],
        language:[{
            type:mongoose.Schema.Types.ObjectId,
            ref:'Languages',
        }],
        TotalDuration:{
            type:String,
        },
        Posterurl:{
            type:String,
            required:true
        },
        trailerurl:{
            type:String,
            required:true
        },
        showType:{
            type:String,
            required:true,
            enum:['Theatre','Online'],
            default:"Theatre"
        },
        AllotedToTheNumberOfTheatres:[{
            type:mongoose.Schema.Types.ObjectId,
            ref:'Theatrees'
        }],
        createdAt:{
            type:String,
            required:true
        },
        castName:[{
            type:mongoose.Schema.Types.ObjectId,
            ref:"Cast"
        }],
        uploaded:{
            type:Boolean,
            default:false,
            required:true
        },
        uploadingTime:{
            type:String,
            required:true,
        },
        VerificationTime:{
            type:Date,
        },
        movieStatus: {
            type: String,
            enum: ["Upcoming", "Released", "Expired","Blocked"],
            default: "Upcoming",
            required:true
        },
        VerifiedByTheAdmin:{
            type:Boolean,
            default:false,
        },
        customeMessage:[{
            type:mongoose.Schema.Types.ObjectId,
            ref:"Message"
        }],
        BannerLiked:{
            type:Number,
            default:0
        },
        Comment:[{
            type:mongoose.Schema.Types.ObjectId,
            ref:"Comment"
        }],
        BannerDisLiked:{
            type:Number,
            default:0
        },
        directorname:[{
            type:String,
            required:true,
            Array:true
        }],
        producername:[{
            type:String,
            required:true
        }],
        writersname:[{
            type:String,
            required:true
        }],
        totalticketsCreated:{
            type:mongoose.Schema.Types.ObjectId,
            ref:'Ticket'
        },
        totalbudget:{
            type:String,
            required:true
        },
        hashtags:[{
            type:mongoose.Schema.Types.ObjectId,
            ref:'Hashtags',
        }],
        movieDuration:{
            type:String,
            required:true
        },
        ratingAndReviews: [
            {
            type: mongoose.Schema.Types.ObjectId,
            ref: "RatingAndReview",
            },
        ],
        ticketspurchased:[{
            type:mongoose.Schema.Types.ObjectId,
            ref:'payment'
        }],
    },{timestamps:true})
    module.exports = mongoose.model('Show',CreateShowSchema)