const mongoose = require('mongoose')
const CreateLanguageSchema =  new mongoose.Schema({
     locationName:{
        type:String,
        required:true,
        unique:true
    },
     locationurl:{
            type:String,
            required:true
        },
        TheatreInsideimages:[{
            type:String,
            required:true
        }],
        Theatreoutsideimages:[{
            type:String,
            required:true
        }],
        typesofseatsAvailable:[{
            type:String,
            required:true
        }],
        CustomMessage:[{
            type:mongoose.Schema.Types.ObjectId,
            ref:'Message'
        }],
        movieScreeningType:[{
            type:String,
            required:true
        }],
        languagesAvailable:[{
            type:String,
            required:true
        }],

    Theatrename:{
        type:String,
        required:true
    },
    theatreformat:[{
        type:String,
        required:true
    }],
    CreationDate:{
        type:String,
    },
    showAlloted:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Show"
    }],
    ticketsReceived:[{
        type:String,
    }],
    ticketsReceivedTime:[{
        type:String,
    }],
    priceoftheTicket:[{
        type:String
    }],
    issues:{
        type:String,
        maxlength:200
    },
    TheatreOwner:{
        type:String,
        required:true
    },
    ticketCreation:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:'CreateTicket'
    }],
    parking:[{
        type:String ,
        required:true
    }],
    Owner:{
         type:mongoose.Schema.Types.ObjectId,
        ref:'User'
    },
    Verified:{
        type:Boolean,
        required:true,
        default:false
    },
    VerifiedAt:{
        type:String
    },
    RejectedAt:{
        type:String
    },
    status:{
        type:String,
        required:true,
        default:"Pending",
        enum :["Pending","Approved","Rejected"]
    }
},{timestamps:true})
module.exports = mongoose.model('Theatrees',CreateLanguageSchema)